### ISSUE TITLE
Schema Events and Access

### ISSUE THREAD

**Issue by brandynbennett** [SpiffInc/polyn-protocol#2]
Every service that uses Polyn needs to publish the events and schemas it produces so that other services can discover and understand them. Event and/or schema changes should be published anytime a service is deployed/comes online so that other services can get updates and be aware of what services are running. The schema events should adhere to the same [CloudEvent Spec](https://github.com/cloudevents/spec) that other events in the system use and follow the same rules. Each Polyn library should take care of setting up the Consumers and Producers for these schema events so that developers can focus on application code unique to their service.

# `polyn.service.started` event definition
When a Polyn application starts, after it has run any schema migrations, it should publish an event called `<reverse.domain>.polyn.service.started` (e.g. `app.spiff.polyn.service.started`) and it should look like this:

```json
{
  "specversion" : "1.0.1",
  "type" : "app.spiff.polyn.service.started.v1",
  "source" : "location or name of service",
  "id" : "a-unique-uuid",
  "time" : "2018-04-05T17:31:00Z",
  "datacontenttype" : "application/json",
  "dataschema": "app.spiff.polyn.service.started.v1.schema.v1.json",
  "data" : {
    "events": {
      "app.spiff.user.created.v2": [
        "app.spiff.user.created.v2.schema.v1.json"
      ],
      "app.spiff.user.created.v1": [
        "app.spiff.user.created.v1.schema.v3.json",
        "app.spiff.user.created.v1.schema.v2.json",
        "app.spiff.user.created.v1.schema.v1.json"
      ],
      "app.spiff.user.updated.v1": [
        "app.spiff.user.updated.v1.schema.v2.json",
        "app.spiff.user.updated.v1.schema.v1.json"
      ] 
    }
  }
}
```

## `polyn.service.started` data definition schema

```json
{
  "$id": "app.spiff.polyn.service.started.v1.schema.v1.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "events": { "type": "object" }
  },
  "required": ["events"]
}
``` 

# Individual Schema Events

In addition to publishing an event that includes all the events the Producer publishes, it will also publish individual events when it detects that a new schema is being published by the Producer. It will be called `polyn.schema.created` and will look something like this:

```json
{
  "specversion" : "1.0.1",
  "type" : "app.spiff.polyn.schema.created.v1",
  "source" : "location or name of service",
  "id" : "a-unique-uuid",
  "time" : "2018-04-05T17:31:00Z",
  "datacontenttype" : "application/json",
  "dataschema": "app.spiff.polyn.schema.created.v1.schema.v1.json",
  "data" : {
    "event": "app.spiff.user.created.v2",
    "schema": {
      "$id": "app.spiff.user.created.v2.schema.v2.json",
      "$schema": "http://json-schema.org/draft-07/schema",
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "username": { "type": "string" }
      },
      "required": ["name", "username"]
    }
  }
}
```

## The Schema for `app.spiff.polyn.schema.created.v1.schema.v1.json`

```json
{
  "$id": "app.spiff.polyn.schema.created.v1.schema.v1.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "event": { "type": "string" },
    "schema": { "type": "object" }
  },
  "required": ["event", "schema"]
}
```

The `polyn.service.started` event will only contain the `ids` of the schemas associated with each event. To access the schema definition associated with each id a Polyn Consumer will first look in its service's internal cache of schemas to see if it has that definition already. If it doesn't have the definition it can attempt to find it by looking at the messages published on `polyn.schema.created` to see if one of them matches the schema id it's lacking. Similarly a Polyn Producer will look through the `polyn.service.started` message to make sure that there are no schemas it's created that are not available in the event bus/transporter.

**Comment by fugufish** [comment]
for the schema event, should it publish the actual schema as a part of the payload?

```json
{
  "specversion" : "1.0.1",
  "type" : "app.spiff.polyn.service.started.v1",
  "source" : "location or name of service",
  "id" : "a-unique-uuid",
  "time" : "2018-04-05T17:31:00Z",
  "datacontenttype" : "application/json",
  "dataschema": "app.spiff.polyn.service.started.v1.schema.v1.json",
  "data" : {
    "events": {
      "app.spiff.user.created.v2":  "serialized json schema",
      "app.spiff.user.created.v1":  "serialized json schema"
    }
  }
}
```

**Comment by brandynbennett** [comment]
I think that would be ideal to have it embedded in the startup event. My worry was about the size of the message if there were a lot of events and schemas in there over time or some really big god object schemas. What do you think? I'm not as familiar with the size limitations of the event systems out there.

**Comment by brandynbennett** [comment]
Maybe we can compress and decompress them so it matters less?

**Comment by brandynbennett** [comment]
Another thought I had is that we should distinguish between the events produced and consumed by the service. This would help give visibility into when an older version of an event or schema is no longer being used so the producer can eliminate the old code path.

**Comment by brandynbennett** [comment]
Now in Readme
